baseURL = 'https://blog.chariot-chaser.net/'
languageCode = 'en-us'
title = "Philip Conrad's Blog"
theme = 'chariot-chaser'
pygmentsUseClasses = true
pygmentsCodefences = true


[menus]
[[menus.main]]
name = 'Philip Conrad'
pageRef = '/'
weight = 10
[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20
[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 30
[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 30
[[menus.main]]
name = 'Github'
url = "https://github.com/philipaconrad"
weight = 40

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'monokai'
tabWidth = 4
